version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports: 
        - "80:80"
        volumes:
            - ./:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf